CREATE DATABASE AnsibleDB;
GO

USE AnsibleDB;
CREATE TABLE Users (
    ID INT PRIMARY KEY,
    Name NVARCHAR(100)
);
GO
CREATE TABLE Orders (
    OrderID INT PRIMARY KEY,
    UserID INT,
    Amount DECIMAL(10, 2),
    FOREIGN KEY (UserID) REFERENCES Users(ID)
);
GO
CREATE TABLE Products (
    ProductID INT PRIMARY KEY,
    ProductName NVARCHAR(100),
    Price DECIMAL(10, 2)
);