# Ansible Inventory File
# Updated: 2025-11-29
# Format: YAML

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:

    # ------------------------------------------------------------------
    # Control Node / Ansible Controller
    # ------------------------------------------------------------------
    control_node:
      hosts:
        ansible-controller:
          ansible_connection: local

    # ------------------------------------------------------------------
    # OpenSCAP scan servers
    # ------------------------------------------------------------------
    # openscap_servers:
    #   hosts:
    #     openscap-AlmaLinux:
    #       ansible_host: 192.168.1.137
    #       ansible_user: suricata
    #       ansible_password: ansible123
    #       ansible_become: yes
    #       ansible_become_method: sudo
    #       ansible_become_password: ansible123

    # ------------------------------------------------------------------
    # Regular Linux servers
    # ------------------------------------------------------------------
    # linux_servers:
    #   hosts:
    #     linux_server:
    #       ansible_host: 192.168.1.137
    #       ansible_user: suricata
    #       ansible_password: ansible123
    #       ansible_become: yes
    #       ansible_become_method: sudo
    #       ansible_become_password: ansible123

    # ------------------------------------------------------------------
    # Targets for scanning (Nmap, OpenVAS, OpenSCAP,…)
    # ------------------------------------------------------------------
    # scan_targets:
    #   hosts:
    #     target1:
    #       ansible_host: 192.168.1.137
    #       scan_ip: 192.168.1.137

    # ------------------------------------------------------------------
    # Zabbix Infrastructure
    # ------------------------------------------------------------------
    # zabbix_server:
    #   hosts:
    #     zabbix-server:
    #       ansible_connection: local
    #       ansible_default_ipv4:
    #         address: 192.168.1.125

    # zabbix_agents:
    #   hosts:
    #     agent-01:
    #       ansible_host: 192.168.1.137
    #       ansible_user: suricata
    #       ansible_password: ansible123  
    #       ansible_become: yes
    #       ansible_become_method: sudo
    #       ansible_become_password: ansible123

    # network_devices:
    #   hosts:
    #     switch-01:
    #       ansible_host: 192.168.1.254
    #       device_type: switch
    #       snmp_community: public

    # ------------------------------------------------------------------
    # Prometheus Infrastructure
    # ------------------------------------------------------------------
    prometheus_servers:
      hosts:
        prometheus-server:
          ansible_host: 192.168.1.29
          ansible_user: ansible
          ansible_password: Admin123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: Admin123
          ansible_default_ipv4:
            address: 192.168.1.29

    monitored_hosts:
      hosts:
        BE-host-01:
          ansible_host: 192.168.1.27
          ansible_user: ansible
          ansible_password: Admin123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: Admin123
        BE-host-02:
          ansible_host: 192.168.1.30
          ansible_user: ansible
          ansible_password: Admin123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: Admin123
        HA-host-01:
          ansible_host: 192.168.1.8
          ansible_user: ansible
          ansible_password: Admin123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: Admin123
        HA-host-02:
          ansible_host: 192.168.1.25
          ansible_user: ansible
          ansible_password: Admin123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: Admin123
        ubuntu:
          ansible_host: 192.168.1.55
          ansible_user: ubuntu01
          ansible_password: Admin123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: Admin123
        Sec:
          ansible_host: 192.168.1.26
          ansible_user: ansible
          ansible_password: Admin123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: Admin123
        Backup:
          ansible_host: 192.168.1.9
          ansible_user: ansible
          ansible_password: Admin123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: Admin123
        

        # WinServer2016:
        #   ansible_host: 192.168.1.18
        #   ansible_user: Administrator
        #   ansible_password: Aa123
        #   ansible_connection: winrm
        #   ansible_winrm_transport: ntlm
        #   # ansible_winrm_transport: basic
        #   ansible_port: 5985
        #   ansible_winrm_server_cert_validation: ignore
         

    # ------------------------------------------------------------------
    # High Availability Load Balancer Infrastructure
    # ------------------------------------------------------------------
    ha_servers:
      hosts:
        HA1:
          ansible_host: 192.168.1.8
          ansible_user: ansible
          ansible_password: Admin123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: Admin123
          keepalived_state: MASTER
          keepalived_priority: 100
        HA2:
          ansible_host: 192.168.1.25
          ansible_user: ansible
          ansible_password: Admin123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: Admin123
          keepalived_state: BACKUP
          keepalived_priority: 90
      vars:
        virtual_ip: 192.168.1.100
        virtual_router_id: 51

    web_servers:
      hosts:
        Web1:
          ansible_host: 192.168.1.27
          ansible_user: ansible
          ansible_password: Admin123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: Admin123
          server_name: WEB-1
          server_color: "#3498db"  # Blue
        Web2:
          ansible_host: 192.168.1.30
          ansible_user: ansible
          ansible_password: Admin123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: Admin123
          server_name: WEB-2
          server_color: "#e74c3c"  # Red

    # ------------------------------------------------------------------
    # Security / IDS Infrastructure
    # ------------------------------------------------------------------
    security_servers:
      hosts:
        IDS-Server:
          ansible_host: 192.168.1.26
          ansible_user: ansible
          ansible_password: Admin123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: Admin123
          suricata_interface: ens192
          suricata_home_net: "[192.168.1.0/24]"
      vars:
        suricata_web_ui_enabled: yes
        suricata_web_ui_port: 8080

    #ADDS winserver
    ADDS_servers:
      hosts:
        WinServer2016:
          ansible_host: 192.168.1.18
          ansible_user: Administrator
          ansible_password: Admin123
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          # ansible_winrm_transport: basic
          ansible_port: 5985
          ansible_winrm_server_cert_validation: ignore
          ansible_become: false        # 👈 QUAN TRỌNG




    # ------------------------------------------------------------------
    # Grafana Monitoring Stack
    # ------------------------------------------------------------------
    monitoring_servers:
      hosts:
        grafana-server:
          ansible_host: 192.168.1.29
          ansible_user: ansible
          ansible_password: Admin123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: Admin123 
          ansible_default_ipv4:
            address: 192.168.1.29
    

    # ------------------------------------------------------------------
    # Wazuh Infrastructure
    # ------------------------------------------------------------------
    # wazuh_server:
    #   hosts:
    #     wazuh-manager:
    #       ansible_connection: local
    #       wazuh_manager_ip: 192.168.1.125

    # wazuh_agents:
    #   hosts:
    #     wazuh-agent-01:
    #       ansible_host: 192.168.1.137
    #       ansible_user: suricata
    #       ansible_password: ansible123
    #       ansible_become: yes
    #       ansible_become_method: sudo
    #       ansible_become_password: ansible123

    #     wazuh-agent-02:
    #       ansible_host: 192.168.1.240
    #       ansible_user: jitsi
    #       ansible_password: ansible123
    #       ansible_become: yes
    #       ansible_become_method: sudo
    #       ansible_become_password: ansible123

    #   vars:
    #     wazuh_manager_ip: 192.168.1.125
    #     wazuh_agent_group: default
    #     wazuh_version: "4.7"

    # ------------------------------------------------------------------
    # Combined Groups
    # ------------------------------------------------------------------

    monitored:
      children:
        zabbix_server: {}
        zabbix_agents: {}
        network_devices: {}

    # wazuh:
    #   children:
    #     wazuh_server: {}
    #     wazuh_agents: {}
