all:
  children:
    linux_servers:
      hosts:
        linux_server:
          ansible_host: 192.168.193.200
          ansible_user: suricata
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
        client:
          ansible_host: 192.168.193.201
          ansible_user: client01
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    win_servers:
      hosts:
        win_server:
          ansible_host: 192.168.193.250
          ansible_user: Administrator
          ansible_password: Aa123
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_port: 5985
          ansible_winrm_server_cert_validation: ignore