# all:
#   children:

#     localhost:
#       hosts:
#         ansible-controller:
#           ansible_connection: local
#           ansible_python_interpreter: /usr/bin/python3


          
#     linux_servers:
#       hosts:
#         linux_server:
#           ansible_host: 192.168.1.69
#           ansible_user: suricata  
#           ansible_password: ansible123
#     scan_targets:
#       hosts:
#         target1:
#           ansible_host: 192.168.1.69
#           scan_ip: 192.168.1.69
 
#     # win_servers:
#     #   hosts:
#     #     win_server:
#     #       ansible_host: 192.168.193.250
#     #       ansible_user: Administrator
#     #       ansible_password: Aa123
#     #       ansible_connection: winrm
#     #       ansible_winrm_transport: ntlm
#     #       # ansible_winrm_transport: basic
#     #       ansible_port: 5985
#     #       ansible_winrm_server_cert_validation: ignore

#     # Zabbix Infrastructure Inventory
# # Updated: 2025-10-19 12:04:19 UTC
# # Author: HyHonCuTe

#     [zabbix_server]
#     localhost ansible_connection=local

#     [zabbix_agents]
#     agent-01 ansible_host=192.168.1.100 ansible_user=admin

#     [network_devices]
#     # SNMP monitoring cho thiết bị mạng
#     switch-01 ansible_host=192.168.1.254 device_type=switch snmp_community=public

#     [monitored:children]
#     zabbix_server
#     zabbix_agents
#     network_devices

#     [all:vars]
#     ansible_python_interpreter=/usr/bin/python3

all:
  children:

    # localhost:
    #   hosts:
    #     ansible-controller:
    #       ansible_connection: local
    #       ansible_python_interpreter: /usr/bin/python3

    linux_servers:
      hosts:
        linux_server:
          ansible_host: 192.168.1.69
          ansible_user: suricata
          ansible_password: ansible123

    scan_targets:
      hosts:
        target1:
          ansible_host: 192.168.1.69
          scan_ip: 192.168.1.69



    zabbix_server:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
          ansible_default_ipv4:
            address: 192.168.1.125

    zabbix_agents:
      hosts:
        agent-01:
          ansible_host: 192.168.1.69
          ansible_user: suricata
          ansible_password: ansible123  # ✅ FIX: Thêm ansible_password
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: ansible123

    network_devices:
      hosts:
        switch-01:
          ansible_host: 192.168.1.254
          device_type: switch
          snmp_community: public

