# Ansible Inventory File
# Updated: 2025-11-29
# Format: YAML

all:
  children:

    localhost:
      hosts:
        ansible-controller:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3

    linux_servers:
      hosts:
        linux_server:
          ansible_host: 192.168.1.137
          ansible_user: suricata
          ansible_password: ansible123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: ansible123

    scan_targets:
      hosts:
        target1:
          ansible_host: 192.168.1.137
          scan_ip: 192.168.1.137

    # Zabbix Infrastructure
    zabbix_server:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
          ansible_default_ipv4:
            address: 192.168.1.125

    zabbix_agents:
      hosts:
        agent-01:
          ansible_host: 192.168.1.137
          ansible_user: suricata
          ansible_password: ansible123  
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: ansible123

    network_devices:
      hosts:
        switch-01:
          ansible_host: 192.168.1.254
          device_type: switch
          snmp_community: public

    # Prometheus Infrastructure
    prometheus_servers:
      hosts:
        prometheus-server:
          ansible_host: localhost
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
          ansible_default_ipv4:
            address: 192.168.1.125
    
    monitored_hosts:
      hosts:
        monitored-host-01:
          ansible_host: 192.168.1.137
          ansible_user: suricata
          ansible_password: ansible123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: ansible123

    # Grafana Monitoring Stack
    monitoring_servers:
      hosts:
        grafana-server:
          ansible_host: localhost
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3

    # Wazuh Infrastructure
    wazuh_server:
      hosts:
        wazuh-manager:
          ansible_host: localhost
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3
          wazuh_manager_ip: 192.168.1.125

    wazuh_agents:
      hosts:
        wazuh-agent-01:
          ansible_host: 192.168.1.137
          ansible_user: suricata
          ansible_password: ansible123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: ansible123
        wazuh-agent-02:
          ansible_host: 192.168.1.240
          ansible_user: jitsi
          ansible_password: ansible123
          ansible_become: yes
          ansible_become_method: sudo
          ansible_become_password: ansible123
      vars:
        wazuh_manager_ip: 192.168.1.125
        wazuh_agent_group: default
        wazuh_version: "4.7"

    # Group definitions
    monitored:
      children:
        zabbix_server
        zabbix_agents
        network_devices

    wazuh:
      children:
        wazuh_server
        wazuh_agents

  vars:
    ansible_python_interpreter: /usr/bin/python3
