all:
  children:
    linux_servers:
      hosts:
        linux_server:
          ansible_host: 10.10.1.151
          ansible_user: suricata  
          ansible_password: ansible123
          
    # win_servers:
    #   hosts:
    #     win_server:
    #       ansible_host: 192.168.193.250
    #       ansible_user: Administrator
    #       ansible_password: Aa123
    #       ansible_connection: winrm
    #       ansible_winrm_transport: ntlm
    #       # ansible_winrm_transport: basic
    #       ansible_port: 5985
    #       ansible_winrm_server_cert_validation: ignore