---
- name: Copy database creation script
  ansible.windows.win_copy:
    src: files/create_db.sql
    dest: C:\SQLScripts\create_db.sql

- name: Execute database creation script
  ansible.windows.win_shell: |
    sqlcmd -S localhost -U sa -P "{{ sa_password }}" -i C:\SQLScripts\create_db.sql
  register: db_creation
  failed_when: db_creation.rc != 0