- name: Kiểm tra xem dịch vụ MSSQLSERVER có tồn tại không
  ansible.windows.win_service:
    name: 'MSSQLSERVER'
  register: service_info

- name: Kết thúc play nếu dịch vụ MSSQLSERVER đã tồn tại
  ansible.builtin.meta: end_play
  when: service_info.exists

- name: Tạo thư mục tạm thời trên máy mục tiêu
  ansible.windows.win_file:
    path: 'C:\\temp'
    state: directory
  when:
    - not service_info.exists

- name: Kiểm tra xem file SQLServer2022-x64-ENU.iso có tồn tại không
  win_stat:
    path: C:\\temp\\SQLServer2022-x64-ENU.iso
  register: file_check

- name: In ra đường dẫn nếu file tồn tại
  debug:
    msg: "File tồn tại tại: {{ file_check.stat.path }}"
  when: file_check.stat.exists

- name: Sao chép file ISO vào máy mục tiêu
  ansible.windows.win_copy:
    src: '/home/server_ansible/ansible/roles/database/files/SQLServer2022-x64-ENU.iso'
    dest: 'C:\\temp\\'
  when:
    - not file_check.stat.exists

- name: Sao chép file cấu hình Configuration.ini vào máy mục tiêu
  ansible.builtin.template:
    src: '/home/server_ansible/ansible/roles/database/files/config2022.j2'
    dest: 'C:\\temp\\Configuration.ini'
  when:
    - not service_info.exists

- name: Gắn file ISO vào ổ đĩa
  community.windows.win_disk_image:
    image_path: 'C:\\temp\\SQLServer2022-x64-ENU.iso'
    state: present
  register: disk_image_out
  when:
    - not service_info.exists

- name: Đặt mật khẩu SA cho SQL Server
  ansible.builtin.set_fact:
    sa_password_switch: "{{ '/SAPWD={{ sql_password }}' }}"
  when:
    - not service_info.exists

- name: Cài đặt instance mặc định của SQL Server
  ansible.windows.win_command:
    cmd: '{{ disk_image_out.mount_paths[0] }}setup.exe /ConfigurationFile=C:\\temp\\Configuration.ini {{ sa_password_switch }}'
  when:
    - not service_info.exists

# - name: Dỡ bỏ mount file ISO
#   community.windows.win_disk_image:
#     image_path: 'C:\\temp\\SQLServer2022-x64-ENU.iso'
#     state: absent
#   when:
#     - not service_info.exists

# - name: Dọn dẹp thư mục tạm thời
#   ansible.windows.win_file:
#     path: 'C:\\temp'
#     state: absent
#   when:
#     - not service_info.exists
