- name: Check if SQL Server is already installed
  ansible.windows.win_service:
    name: 'MSSQLSERVER'
  register: service_info

- name: End play if SQL Server is already installed
  ansible.builtin.meta: end_play
  when: service_info.exists

- name: Create temp folder on target machine
  ansible.windows.win_file:
    path: 'C:\temp'
    state: directory

- name: Set Windows power plan to high performance
  community.windows.win_power_plan:
    name: high performance

- name: Copy SQL Server installer (SSEI) to target machine
  ansible.windows.win_copy:
    src: '/home/server_ansible/ansible/roles/database/files/SQL2019-SSEI-Expr.exe'  # Đảm bảo file .exe có sẵn trên máy controller
    dest: 'C:\temp\SQL2019-SSEI-Expr.exe'

- name: Copy configuration file to target machine
  ansible.builtin.template:
    src: './config2019.j2'  # Đảm bảo file cấu hình không có mật khẩu và sử dụng Windows Authentication
    dest: 'C:\temp\Configuration.ini'

- name: Run SQL Server installer
  ansible.windows.win_command:
    cmd: 'C:\temp\SQL2019-SSEI-Expr.exe /ConfigurationFile=C:\temp\Configuration.ini'

- name: Cleanup temp directory
  ansible.windows.win_file:
    path: 'C:\temp'
    state: absent