
    - name: Ensure restore folder exists on Windows
      win_file:
        path: "{{ remote_backup_dir }}"
        state: directory

    - name: Upload all .bak files to Windows
      win_copy:
        src: "{{ item }}"
        dest: "{{ remote_backup_dir }}\\"
      loop: "{{ lookup('fileglob', local_backup_dir + '/*.bak', wantlist=True) }}"

    - name: Restore all uploaded databases
      win_shell: |
        $files = Get-ChildItem -Path "{{ remote_backup_dir }}" -Filter *.bak
        foreach ($file in $files) {
            $name = $file.BaseName.Split('_')[0]

            # Lấy danh sách session đang dùng database $name
            $sessions = Invoke-Sqlcmd -ServerInstance "localhost" -Query "
                SELECT session_id FROM sys.dm_exec_sessions 
                WHERE database_id = DB_ID('$name') AND session_id <> @@SPID
            "
            
            # Kill từng session đang kết nối database
            foreach ($session in $sessions) {
                $sid = $session.session_id
                Invoke-Sqlcmd -ServerInstance "localhost" -Query "KILL $sid"
            }

            # Restore database
            Restore-SqlDatabase -ServerInstance "localhost" -Database $name -BackupFile $file.FullName -ReplaceDatabase
        }
      args:
        executable: powershell
