- name: Install DHCP Server Role
  ansible.windows.win_feature:
    name: DHCP
    include_management_tools: yes
  register: dhcp_install




- name: Reboot if required
  ansible.windows.win_reboot:
  when: dhcp_install.reboot_required

- name: Configure DNS
  ansible.windows.win_dns_client:
    adapter_names: "Ethernet0"
    dns_servers: "192.168.193.250"
  tags: dns

- name: Join Domain
  ansible.windows.win_domain_membership:
    dns_domain_name: "vodaohuyhoang.com"
    domain_admin_user: "vodaohuyhoang\\Administrator"  # Đổi từ UPN sang format DOMAIN\\username
    domain_admin_password: "Aa123"
    state: domain
    domain_ou_path: "OU=Computers,DC=vodaohuyhoang,DC=com"
  register: domain_join
  tags: domain_join

- name: Reboot after domain join
  ansible.windows.win_reboot:
  when: domain_join.reboot_required
  tags: domain_join


- name: Tạo nhóm DHCP Admins bằng PowerShell
  ansible.windows.win_shell: |
    New-ADGroup `
      -Name "DHCP_Admins" `
      -GroupScope DomainLocal `
      -Description "Nhóm quản trị DHCP Server" `
      -PassThru
  become: yes
  become_method: runas
  become_user: "Administrator@vodaohuyhoang.com"
  args:
    become_password: "Aa123"

- name: Thêm user vào nhóm
  ansible.windows.win_shell: |
    Add-ADGroupMember `
      -Identity "DHCP_Admins" `
      -Members "ansible_user@vodaohuyhoang.com"
  become: yes
  become_method: runas
  become_user: "Administrator@vodaohuyhoang.com"
  args:
    become_password: "Aa123"

- name: Authorize DHCP Server trong AD
  ansible.windows.win_shell: |
    Add-DhcpServerInDC -DnsName "{{ ansible_fqdn }}"
  become: yes
  become_method: runas
  become_user: "Administrator@vodaohuyhoang.com"
  args:
    become_password: "Aa123"