{
 "title": "Zabbix Server Monitoring",
 "tags": [
  "zabbix",
  "monitoring"
 ],
 "refresh": "1m",
 "panels": [
  {
   "title": "Monitored Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "group": { "filter": "" }, "host": { "filter": "" }, "application": { "filter": "" }, "item": { "filter": "Number of monitored hosts" } }
   ]
  },
  {
   "title": "Active Triggers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "group": { "filter": "" }, "host": { "filter": "" }, "application": { "filter": "" }, "item": { "filter": "Number of enabled triggers" } }
   ]
  },
  {
   "title": "Active Items",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "group": { "filter": "" }, "host": { "filter": "" }, "application": { "filter": "" }, "item": { "filter": "Number of enabled items" } }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "group": { "filter": "" }, "host": { "filter": "Zabbix server" }, "application": { "filter": "" }, "item": { "filter": "Zabbix server: Uptime" } }
   ]
  },
  {
   "title": "Active Problems by Severity",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "mode": 4, "triggers": { "minSeverity": 0 } }
   ]
  },
  {
   "title": "Problems History",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "mode": 4, "triggers": { "minSeverity": 2 } }
   ]
  },
  {
   "title": "Host Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "itemFilter": ".*" }
   ]
  },
  {
   "title": "Zabbix Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "group": { "filter": "" }, "host": { "filter": "Zabbix server" }, "application": { "filter": "" }, "item": { "filter": "Zabbix queue" } }
   ]
  },
  {
   "title": "Items Processing Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "group": { "filter": "" }, "host": { "filter": "Zabbix server" }, "application": { "filter": "" }, "item": { "filter": "Values processed per second" } }
   ]
  }
 ]
}