---
# Zabbix deployment main tasks
# Author: HyHonCuTe
# Updated: 2025-10-19 13:09:41 UTC

- name: "Display deployment info"
  debug:
    msg: |
      ╔════════════════════════════════════════════════╗
      ║   Zabbix Role Starting                         ║
      ║   Host: {{ inventory_hostname }}               ║
      ║   Groups: {{ group_names }}                    ║
      ║   Time: {{ ansible_date_time.iso8601 }}        ║
      ╚════════════════════════════════════════════════╝

# Zabbix Server installation
- name: "Include Zabbix Server installation"
  include_tasks: install_server.yml
  when: "'zabbix_server' in group_names"
  tags:
    - zabbix_server
    - install

# Zabbix Server configuration
- name: "Include Zabbix Server configuration"
  include_tasks: configure_server.yml
  when: "'zabbix_server' in group_names"
  tags:
    - zabbix_server
    - configure

# Setup monitoring
- name: "Include monitoring setup"
  include_tasks: setup_monitoring.yml
  when: "'zabbix_server' in group_names"
  tags:
    - zabbix_server
    - monitoring

# Zabbix Agent installation
- name: "Include Zabbix Agent installation"
  include_tasks: install_agent.yml
  when: "'zabbix_agents' in group_names or 'zabbix_server' in group_names"
  tags:
    - zabbix_agents
    - install

# Zabbix Agent configuration
- name: "Include Zabbix Agent configuration"
  include_tasks: configure_agent.yml
  when: "'zabbix_agents' in group_names or 'zabbix_server' in group_names"
  tags:
    - zabbix_agents
    - configure

- name: "Include add host to Zabbix Server"
  include_tasks: add_host.yml
  when: "'zabbix_agents' in group_names"
  tags:
    - add_host
    - zabbix_agents