- name: Kiểm tra tính năng trên Windows Server
  hosts: all
  gather_facts: true
  vars:
    webserver_tasks:
      - get_features
  roles:
    - role: webserver
      become: false
  tags: check_features