---
- name: Cập nhật bản vá cho máy chủ Windows
  hosts: win_server
  gather_facts: yes
  roles:
    - role: patching
  tags: patch_windows

- name: Cập nhật bản vá cho máy chủ Linux
  hosts: linux_servers
  gather_facts: yes
  become: yes
  roles:
    - role: patching
  tags: patch_linux
