---
- name: Patching Windows Server
  hosts: win_server
  gather_facts: yes
  roles:
    - role: patching
  tags: patch_windows


- name: Patching Linux Server
  hosts: linux_server
  gather_facts: yes
  roles:
    - role: patching
  tags: patch_linux
