---
- name: Test ping các host
  hosts: all
  gather_facts: true
  roles:
    - role: common
      become: "{{ ansible_os_family != 'Windows' }}"
  tags: ping      

- name: Test check Features
  hosts: win_server
  gather_facts: true
  vars:
    webserver_tasks:
      - get_features
  roles:
    - role: webserver
      become: false
  tags: check_features

- name: Test Install web
  hosts: win_server
  gather_facts: true
  vars:
    webserver_tasks:
      - install_iis
      - deploy_site
      - check_site
  roles:
    - role: webserver
      become: false
  tags: install_web

- name: Cài SQL Server Developer bằng Ansible
  hosts: win_server
  vars:
    sql_sa_password: "Aa123"
  gather_facts: false
  roles:
    - role: database
      become: false
  tags: install_sql


- name: Cài DNS Server trên Windows
  hosts: win_server
  gather_facts: yes
  collections:
    - ansible.windows
  roles:
    - dns
  tags:
    - install_dns




