---
- name: Kiểm tra kết nối các host bằng ping
  hosts: all
  gather_facts: true
  roles:
    - role: common
      become: "{{ ansible_os_family != 'Windows' }}"
  tags: ping

- name: Kiểm tra tính năng trên Windows Server
  hosts: win_server
  gather_facts: true
  vars:
    webserver_tasks:
      - get_features
  roles:
    - role: webserver
      become: false
  tags: check_features

- name: Cài đặt Web Server và triển khai Website
  hosts: win_server
  gather_facts: true
  vars:
    webserver_tasks:
      - install_iis
      - deploy_site
      - check_site
  roles:
    - role: webserver
      become: false
  tags: install_web

- name: Cài đặt SQL Server trên Windows
  hosts: win_server
  gather_facts: no
  collections:
    - ansible.windows
  roles:
    - database
  tags:
    - install_database

- name: Cài đặt DNS Server trên Windows
  hosts: win_server
  gather_facts: yes
  collections:
    - ansible.windows
  roles:
    - dns
  tags:
    - install_dns

# - name: Cài đặt DHCP Server trên Windows
#   hosts: win_server
#   gather_facts: yes
#   collections:
#     - ansible.windows
#   roles:
#     - dhcp
#   tags:
#     - install_dhcp

- name: Cài đặt tường lửa (Firewall) trên Linux
  hosts: linux_server
  gather_facts: true
  roles:
    - role: firewall
      become: true
  tags:
    - install_firewall

- name: Tạo người dùng trên Linux
  hosts: linux_server
  gather_facts: true
  roles:
    - role: user
      become: true
  tags:
    - install_user

- name: Cài đặt hệ thống Backup trên Linux
  hosts: linux_servers
  gather_facts: true
  roles:
    - role: backup
      become: true
  tags:
    - install_backup


- name: Cài đặt Suricata trên Linux
  hosts: client
  gather_facts: true
  roles:
    - role: suricata
      become: true
  tags:
    - install_suricata    


- name: Cài đặt hệ thống Backup trên Windows
  hosts: win_server
  gather_facts: true
  roles:
    - role: backup
      become: false
  tags:
    - install_backupdb
