---
- name: Test ping các host
  hosts: all
  gather_facts: true
  roles:
    - role: common
      become: "{{ ansible_os_family != 'Windows' }}"
  tags: ping      

- name: Test check Features
  hosts: win_server
  gather_facts: true
  vars:
    webserver_tasks:
      - get_features
  roles:
    - role: webserver
      become: false
  tags: check_features

- name: Test Install web
  hosts: win_server
  gather_facts: true
  vars:
    webserver_tasks:
      - install_iis
      - deploy_site
      - check_site
  roles:
    - role: webserver
      become: false
  tags: install_web

- name: Cài SQL Server trên Windows
  hosts: win_server
  gather_facts: no
  collections:
    - ansible.windows
  roles:
    - database
  tags:
    - install_database


- name: Cài DNS Server trên Windows
  hosts: win_server
  gather_facts: yes
  collections:
    - ansible.windows
  roles:
    - dns
  tags:
    - install_dns


# - name: Cài DHCP Server trên Windows
#   hosts: win_server
#   gather_facts: yes
#   collections:
#     - ansible.windows
#   roles:
#     - dhcp
#   tags:
#     - install_dhcp


- name: Cài đặt Firewall trên Linux
  hosts: linux_server
  gather_facts: true
  roles:
    - role: firewall
      become: true
  tags:
    - install_firewall

- name: Cai user
  hosts: linux_server
  gather_facts: true
  roles:
    - role: user
      become: true
  tags:
    - install_user  

- name: Cài đặt Backup
  hosts: linux_servers
  gather_facts: true
  roles:
    - role: backup
      become: true
  tags:
    - install_backup







